plugins {
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'java'
	id 'jacoco'
}

group = 'co.com.srdejo.trazabilidad'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(26)
	}
}

jacoco {
	toolVersion = "0.8.15"
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

ext {
	springBootVersion = "4.1.1"
	mapstructVersion = "1.5.2.Final"
	lombokVersion = "1.18.46"
	lombokMapstructBindingVersion = "0.2.0"
	openApiVersion = "2.8.6"
	springSecurityCrypto = "7.0.7"
	ioJWTVersion = "0.13.0"
}

dependencies {
	implementation "org.springframework.boot:spring-boot-starter-data-mongodb:${springBootVersion}"
	implementation "org.springframework.boot:spring-boot-starter-validation:${springBootVersion}"
	implementation "org.springframework.boot:spring-boot-starter-web:${springBootVersion}"
	implementation "org.springframework.security:spring-security-crypto:${springSecurityCrypto}"
	implementation "org.springframework.boot:spring-boot-starter-security:${springBootVersion}"
	implementation "io.jsonwebtoken:jjwt-api:${ioJWTVersion}"

	developmentOnly "org.springframework.boot:spring-boot-devtools:${springBootVersion}"

	testImplementation "org.springframework.security:spring-security-test"
	testImplementation "org.springframework.boot:spring-boot-starter-test:${springBootVersion}"
	testImplementation "org.springframework.boot:spring-boot-webmvc-test:${springBootVersion}"

	runtimeOnly "io.jsonwebtoken:jjwt-impl:${ioJWTVersion}"
	runtimeOnly "io.jsonwebtoken:jjwt-jackson:${ioJWTVersion}"

	implementation "org.mapstruct:mapstruct:${mapstructVersion}"
	compileOnly "org.projectlombok:lombok:${lombokVersion}"
	annotationProcessor "org.projectlombok:lombok-mapstruct-binding:${lombokMapstructBindingVersion}"
	annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
	annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

	implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${openApiVersion}"
}

tasks.named('test') {
	useJUnitPlatform()
}

test {
	finalizedBy jacocoTestReport
}