server:
  port: 8084

spring:
  mongodb:
    uri: mongodb+srv://${DB_USER}:${DB_PASS}@${DB_HOST}/pragma?appName=srdejo

jwt:
  secret: ${JWT_SECRET:una-clave-secreta-de-al-menos-32-bytes}

appDescription: "Pragma Powerup"
appVersion: "1.0.0"
